package com.hemouna.entidade;
// Generated 13/10/2013 18:18:00 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Bolsadesangue generated by hbm2java
 */
public class Bolsadesangue  implements java.io.Serializable {


     private Integer id;
     private Sangue sangue;
     private Tipobolsa tipobolsa;
     private Hospital hospital;
     private String validade;
     private int saida;
     private Set pacienteHasBolsadesangues = new HashSet(0);

    public Bolsadesangue() {
    }

	
    public Bolsadesangue(Sangue sangue, Tipobolsa tipobolsa, Hospital hospital, String validade, int saida) {
        this.sangue = sangue;
        this.tipobolsa = tipobolsa;
        this.hospital = hospital;
        this.validade = validade;
        this.saida = saida;
    }
    public Bolsadesangue(Sangue sangue, Tipobolsa tipobolsa, Hospital hospital, String validade, int saida, Set pacienteHasBolsadesangues) {
       this.sangue = sangue;
       this.tipobolsa = tipobolsa;
       this.hospital = hospital;
       this.validade = validade;
       this.saida = saida;
       this.pacienteHasBolsadesangues = pacienteHasBolsadesangues;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Sangue getSangue() {
        return this.sangue;
    }
    
    public void setSangue(Sangue sangue) {
        this.sangue = sangue;
    }
    public Tipobolsa getTipobolsa() {
        return this.tipobolsa;
    }
    
    public void setTipobolsa(Tipobolsa tipobolsa) {
        this.tipobolsa = tipobolsa;
    }
    public Hospital getHospital() {
        return this.hospital;
    }
    
    public void setHospital(Hospital hospital) {
        this.hospital = hospital;
    }
    public String getValidade() {
        return this.validade;
    }
    
    public void setValidade(String validade) {
        this.validade = validade;
    }
    public int getSaida() {
        return this.saida;
    }
    
    public void setSaida(int saida) {
        this.saida = saida;
    }
    public Set getPacienteHasBolsadesangues() {
        return this.pacienteHasBolsadesangues;
    }
    
    public void setPacienteHasBolsadesangues(Set pacienteHasBolsadesangues) {
        this.pacienteHasBolsadesangues = pacienteHasBolsadesangues;
    }




}


