package com.hemouna.entidade;
// Generated 26/10/2013 16:53:18 by Hibernate Tools 3.6.0



/**
 * Bolsadesangue generated by hbm2java
 */
public class Bolsadesangue  implements java.io.Serializable {


     private Integer id;
     private Paciente paciente;
     private Tiposangue tiposangue;
     private Tipobolsa tipobolsa;
     private Hospital hospital;
     private String validade;
     private String datasaida;

    public Bolsadesangue() {
    }

	
    public Bolsadesangue(Tiposangue tiposangue, Tipobolsa tipobolsa, Hospital hospital, String validade) {
        this.tiposangue = tiposangue;
        this.tipobolsa = tipobolsa;
        this.hospital = hospital;
        this.validade = validade;
    }
    public Bolsadesangue(Paciente paciente, Tiposangue tiposangue, Tipobolsa tipobolsa, Hospital hospital, String validade, String datasaida) {
       this.paciente = paciente;
       this.tiposangue = tiposangue;
       this.tipobolsa = tipobolsa;
       this.hospital = hospital;
       this.validade = validade;
       this.datasaida = datasaida;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Tiposangue getTiposangue() {
        return this.tiposangue;
    }
    
    public void setTiposangue(Tiposangue tiposangue) {
        this.tiposangue = tiposangue;
    }
    public Tipobolsa getTipobolsa() {
        return this.tipobolsa;
    }
    
    public void setTipobolsa(Tipobolsa tipobolsa) {
        this.tipobolsa = tipobolsa;
    }
    public Hospital getHospital() {
        return this.hospital;
    }
    
    public void setHospital(Hospital hospital) {
        this.hospital = hospital;
    }
    public String getValidade() {
        return this.validade;
    }
    
    public void setValidade(String validade) {
        this.validade = validade;
    }
    public String getDatasaida() {
        return this.datasaida;
    }
    
    public void setDatasaida(String datasaida) {
        this.datasaida = datasaida;
    }




}


