package com.hemouna.entidade;
// Generated 26/10/2013 16:53:18 by Hibernate Tools 3.6.0

/**
 * Hospital generated by hbm2java
 */
public class Hospital implements java.io.Serializable {

    private Integer id;
    private String nomehosp;
    private String login;
    private String senha;
    private int primeirologin;

    public Hospital() {
    }

    public Hospital(String nomehosp, String login, String senha, int primeirologin) {
        this.nomehosp = nomehosp;
        this.login = login;
        this.senha = senha;
        this.primeirologin = primeirologin;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNomehosp() {
        return this.nomehosp;
    }

    public void setNomehosp(String nomehosp) {
        this.nomehosp = nomehosp;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getSenha() {
        return this.senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    public int getPrimeirologin() {
        return this.primeirologin;
    }

    public void setPrimeirologin(int primeirologin) {
        this.primeirologin = primeirologin;
    }

}
