package com.hemouna.entidade;
// Generated 13/10/2013 18:18:00 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hospital generated by hbm2java
 */
public class Hospital  implements java.io.Serializable {


     private Integer id;
     private String nomehosp;


    public Hospital() {
    }

	
    public Hospital(String nomehosp) {
        this.nomehosp = nomehosp;
    }

   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNomehosp() {
        return this.nomehosp;
    }
    
    public void setNomehosp(String nomehosp) {
        this.nomehosp = nomehosp;
    }
   
  
    
 




}


