package com.hemouna.entidade;
// Generated 28/10/2013 09:47:21 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hospital generated by hbm2java
 */
@Entity
@Table(name = "hospital", catalog = "hemounadb"
)
public class Hospital implements java.io.Serializable {

    private Integer id;
    private String nomehosp;
    private String login;
    private String senha;
    private int primeirologin;

    public Hospital() {
    }

    public Hospital(String nomehosp, String login, String senha, int primeirologin) {
        this.nomehosp = nomehosp;
        this.login = login;
        this.senha = senha;
        this.primeirologin = primeirologin;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "nomehosp", nullable = false, length = 50)
    public String getNomehosp() {
        return this.nomehosp;
    }

    public void setNomehosp(String nomehosp) {
        this.nomehosp = nomehosp;
    }

    @Column(name = "login", nullable = false, length = 45)
    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    @Column(name = "senha", nullable = false, length = 45)
    public String getSenha() {
        return this.senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    @Column(name = "primeirologin", nullable = false)
    public int getPrimeirologin() {
        return this.primeirologin;
    }

    public void setPrimeirologin(int primeirologin) {
        this.primeirologin = primeirologin;
    }

}
