package com.hemouna.entidade;
// Generated 13/10/2013 18:18:00 by Hibernate Tools 3.2.1.GA



/**
 * PacienteHasBolsadesangue generated by hbm2java
 */
public class PacienteHasBolsadesangue  implements java.io.Serializable {


     private PacienteHasBolsadesangueId id;
     private Bolsadesangue bolsadesangue;
     private Paciente paciente;
     private String datasaida;

    public PacienteHasBolsadesangue() {
    }

    public PacienteHasBolsadesangue(PacienteHasBolsadesangueId id, Bolsadesangue bolsadesangue, Paciente paciente, String datasaida) {
       this.id = id;
       this.bolsadesangue = bolsadesangue;
       this.paciente = paciente;
       this.datasaida = datasaida;
    }
   
    public PacienteHasBolsadesangueId getId() {
        return this.id;
    }
    
    public void setId(PacienteHasBolsadesangueId id) {
        this.id = id;
    }
    public Bolsadesangue getBolsadesangue() {
        return this.bolsadesangue;
    }
    
    public void setBolsadesangue(Bolsadesangue bolsadesangue) {
        this.bolsadesangue = bolsadesangue;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public String getDatasaida() {
        return this.datasaida;
    }
    
    public void setDatasaida(String datasaida) {
        this.datasaida = datasaida;
    }




}


