package com.hemouna.entidade;
// Generated 26/10/2013 16:53:18 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente implements java.io.Serializable {

    private Integer id;
    private Tiposangue tiposangue;
    private Hospital hospital;
    private String cpf;
    private String nome;

    public Paciente() {
    }

    public Paciente(Tiposangue tiposangue, Hospital hospital, String cpf, String nome) {
        this.tiposangue = tiposangue;
        this.hospital = hospital;
        this.cpf = cpf;
        this.nome = nome;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Tiposangue getTiposangue() {
        return this.tiposangue;
    }

    public void setTiposangue(Tiposangue tiposangue) {
        this.tiposangue = tiposangue;
    }

    public Hospital getHospital() {
        return this.hospital;
    }

    public void setHospital(Hospital hospital) {
        this.hospital = hospital;
    }

    public String getCpf() {
        return this.cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

}
