package com.hemouna.entidade;
// Generated 13/10/2013 18:18:00 by Hibernate Tools 3.2.1.GA



/**
 * PacienteHasBolsadesangueId generated by hbm2java
 */
public class PacienteHasBolsadesangueId  implements java.io.Serializable {


     private int pacienteId;
     private int bolsadesangueId;

    public PacienteHasBolsadesangueId() {
    }

    public PacienteHasBolsadesangueId(int pacienteId, int bolsadesangueId) {
       this.pacienteId = pacienteId;
       this.bolsadesangueId = bolsadesangueId;
    }
   
    public int getPacienteId() {
        return this.pacienteId;
    }
    
    public void setPacienteId(int pacienteId) {
        this.pacienteId = pacienteId;
    }
    public int getBolsadesangueId() {
        return this.bolsadesangueId;
    }
    
    public void setBolsadesangueId(int bolsadesangueId) {
        this.bolsadesangueId = bolsadesangueId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PacienteHasBolsadesangueId) ) return false;
		 PacienteHasBolsadesangueId castOther = ( PacienteHasBolsadesangueId ) other; 
         
		 return (this.getPacienteId()==castOther.getPacienteId())
 && (this.getBolsadesangueId()==castOther.getBolsadesangueId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPacienteId();
         result = 37 * result + this.getBolsadesangueId();
         return result;
   }   


}


