package com.hemouna.entidade;
// Generated 13/10/2013 18:18:00 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Sangue generated by hbm2java
 */
public class Sangue  implements java.io.Serializable {


     private Integer id;
     private String tiposangue;
     private Set pacientes = new HashSet(0);
     private Set bolsadesangues = new HashSet(0);

    public Sangue() {
    }

	
    public Sangue(String tiposangue) {
        this.tiposangue = tiposangue;
    }
    public Sangue(String tiposangue, Set pacientes, Set bolsadesangues) {
       this.tiposangue = tiposangue;
       this.pacientes = pacientes;
       this.bolsadesangues = bolsadesangues;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTiposangue() {
        return this.tiposangue;
    }
    
    public void setTiposangue(String tiposangue) {
        this.tiposangue = tiposangue;
    }
    public Set getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set pacientes) {
        this.pacientes = pacientes;
    }
    public Set getBolsadesangues() {
        return this.bolsadesangues;
    }
    
    public void setBolsadesangues(Set bolsadesangues) {
        this.bolsadesangues = bolsadesangues;
    }




}


