package com.hemouna.entidade;
// Generated 13/10/2013 18:18:00 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Sangue generated by hbm2java
 */
public class Sangue  implements java.io.Serializable {


     private Integer id;
     private String tiposangue;

    public Sangue() {
    }

	
    public Sangue(String tiposangue) {
        this.tiposangue = tiposangue;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTiposangue() {
        return this.tiposangue;
    }
    
    public void setTiposangue(String tiposangue) {
        this.tiposangue = tiposangue;
    }
}


