package com.hemouna.entidade;
// Generated 27/10/2013 19:16:15 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Tipobolsa generated by hbm2java
 */
public class Tipobolsa implements java.io.Serializable {

    private Integer id;
    private String nomebolsa;
    private Set<Bolsadesangue> bolsadesangues = new HashSet(0);

    public Tipobolsa() {
    }

    public Tipobolsa(String nomebolsa) {
        this.nomebolsa = nomebolsa;
    }

    public Tipobolsa(String nomebolsa, Set<Bolsadesangue> bolsadesangues) {
        this.nomebolsa = nomebolsa;
        this.bolsadesangues = bolsadesangues;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNomebolsa() {
        return this.nomebolsa;
    }

    public void setNomebolsa(String nomebolsa) {
        this.nomebolsa = nomebolsa;
    }

    public Set<Bolsadesangue> getBolsadesangues() {
        return this.bolsadesangues;
    }

    public void setBolsadesangues(Set<Bolsadesangue> bolsadesangues) {
        this.bolsadesangues = bolsadesangues;
    }

}
