package com.hemouna.entidade;
// Generated 26/10/2013 16:53:18 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Tiposangue generated by hbm2java
 */
public class Tiposangue implements java.io.Serializable {

    private Integer id;
    private String tiposangue;

    public Tiposangue() {
    }

    public Tiposangue(String tiposangue) {
        this.tiposangue = tiposangue;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTiposangue() {
        return this.tiposangue;
    }

    public void setTiposangue(String tiposangue) {
        this.tiposangue = tiposangue;
    }

}
