package com.hemouna.entidade;
// Generated 13/10/2013 18:18:00 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Tipobolsa generated by hbm2java
 */
public class Tipobolsa implements java.io.Serializable {

    private Integer id;
    private String nomebolsa;

    public Tipobolsa() {
    }

    public Tipobolsa(String nomebolsa) {
        this.nomebolsa = nomebolsa;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNomebolsa() {
        return this.nomebolsa;
    }

    public void setNomebolsa(String nomebolsa) {
        this.nomebolsa = nomebolsa;
    }
}
