package com.hemouna.entidade;
// Generated 13/10/2013 18:18:00 by Hibernate Tools 3.2.1.GA



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer id;
     private Hospital hospital;
     private String login;
     private String senha;
     private int primeirologin;

    public Usuarios() {
    }

    public Usuarios(Hospital hospital, String login, String senha, int primeirologin) {
       this.hospital = hospital;
       this.login = login;
       this.senha = senha;
       this.primeirologin = primeirologin;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Hospital getHospital() {
        return this.hospital;
    }
    
    public void setHospital(Hospital hospital) {
        this.hospital = hospital;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public int getPrimeirologin() {
        return this.primeirologin;
    }
    
    public void setPrimeirologin(int primeirologin) {
        this.primeirologin = primeirologin;
    }




}


